FROM python:3.10

RUN --mount=target=/requirements,type=bind,source=requirements <<EOF
    set -ex

    apt update

    apt --yes install git

    pip install typeguard -r /requirements/requirements.python.test.txt
EOF
